# .github/actions/check-env-vars/action.yml
name: "Check Environment Variables"
description: "Checks if specified environment variables are set in the current environment."
inputs:
  variables:
    description: "A comma-separated list of environment variable names to check."
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check if environment variables are set
      shell: bash
      run: |
        # Split the input string into an array
        IFS=',' read -ra VAR_ARRAY <<< "${{ inputs.variables }}"

        # Iterate over the array and check if each variable is set
        for VAR in "${VAR_ARRAY[@]}"; do
          if [[ -z "${!VAR}" ]]; then
            echo "$VAR is empty or not set"
            exit 1
          else
            echo "$VAR is set"
          fi
        done
