name: Deploy to Vercel

on:
  workflow_run:
    workflows: [Test and Build]
    types:
      - completed

jobs:

  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Tests failed.'

  exit:
    needs: failure
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Tests completed successfully.'

  deploy-to-vercel:
    needs: success
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
